### ISSUE TITLE
Update the imported chummer resources.

### ISSUE THREAD

**Issue by UrsZeidler** [UrsZeidler/shr5rcp#1]
As the chummer resources works in a generic way, the resources with a range of values need concrete representation, eg. cyberware.
Also the selectable skills and skill groups of the shr5 system need to be set.

**Comment by NoxMortem** [comment]
Does this mean we can close this issue?

**Comment by UrsZeidler** [comment]
Why not, we have quite a lot chummer resources related issues opened.
