### ISSUE TITLE
Display of Edge

### ISSUE THREAD

**Issue by NoxMortem** [UrsZeidler/shr5rcp#123]
I suggest the following changes:

* Remove edge from the "State" box but give it its own "Edge" box.
* Change the edge display from Textfield to colored graphics as for Physical, Mental and Overdead
* It makes more sense to change the used edge to "Current Edge" so instead of having 2/6 which means 2 of 6 points are used it would be 2/6 points are still available.

**Comment by UrsZeidler** [comment]
Nice.
It also makes more sense making the widget user change aware.
