### ISSUE TITLE
Add external link storage for files and websites

### ISSUE THREAD

**Issue by NoxMortem** [UrsZeidler/shr5rcp#125]
It should be possible to add external files and links open them with the system tool. This would give the program a huge set of new possibilities like

* Adding external character sheets, notes. This helps the GM to keep track of files.
* Adding links does allow the GM to keep links to common shadowrun wikis.
* Add links to image files (character images, maps)

Should be very cheap to implement. It is not necessary that the program itself implements viewers for all the possible filetypes but .pdf might be clever as in  #71 .

This should be a 1:N relationship. One entity should be able to store links to N objects.

http://stackoverflow.com/questions/2546968/open-pdf-file-on-fly-from-java-application

**Comment by UrsZeidler** [comment]
I thought so too.
This makes sense for the placements, where these stuff may be needed while in game play.
 
Also for the model to text/svg/pdf transformations.

**Comment by UrsZeidler** [comment]
The linux support is not very good implemented in the awt Destop Class, so i have taken a solution from mightypork:
http://stackoverflow.com/questions/18004150/desktop-api-is-not-supported-on-the-current-platform
