### ISSUE TITLE
Missing nodes (red triangle) need tooltips

### ISSUE THREAD

**Issue by NoxMortem** [UrsZeidler/shr5rcp#131]
Example: Feuerwaffe Ares Archon Heavy MP Laser, i am unable to find what is missing in the current model without trial and error. This makes it very difficult to find bugs, missing resources etc.

Suggestion: As the model explorer is able to identify something is missing (red triangle) this red triangle should be added to the fields required.

For example, the runtime does not seem to "require" a skill but the range was required.

**Comment by UrsZeidler** [comment]
This is something for the explorer view #112 , as I found no way to display the validation result. It is in the hands of the ecp project.
