### ISSUE TITLE
Search needs to be less strict

### ISSUE THREAD

**Issue by NoxMortem** [UrsZeidler/shr5rcp#132]
Open Object. If I type "Ares Pr" I expect to find the Ares Predator. Because of the current system I need to type exactly "Feuerwaffe Ares Pr" because it seems to look how the nodes name starts.

"Ares Pr" should find all products containing "Ares Pr" inside of their name.

Other searches behave exactly like this (example: search in range window)

**Comment by gixxy** [comment]
You can to use the wild card character, *. If you search *Ares Pr (with the asterisk) it will appear. (Basically translates to: find, 0 or more characters, then Ares Pr)

**Comment by UrsZeidler** [comment]
Thanks to @gixxy.  in addition, you could also use '?'  for just one literal.
