### ISSUE TITLE
Munition type

### ISSUE THREAD

**Issue by NoxMortem** [UrsZeidler/shr5rcp#137]
It is unable to remove a selected type as there is no type "Nothing".

There is also no correct selection possible. APDS munition for example is available for most weapons, why is this linked with a range node?

**Comment by UrsZeidler** [comment]
'Nothing' is the last, and also empty item in the dialog.
see #191

**Comment by NoxMortem** [comment]
Ah its absolutely blank under windows 7 until i hover it. I would recommend a "Nothing" Dummy item instead. (Usability)
