### ISSUE TITLE
Missing description

### ISSUE THREAD

**Issue by NoxMortem** [UrsZeidler/shr5rcp#151]
Almost all resources lack any text in the description field.

**Comment by UrsZeidler** [comment]
Don't know where to take it from.
Also there should be an legal issue, as we do not have the rights, 'Hero Lab' got it.

**Comment by NoxMortem** [comment]
I think the best would be user written decriptions which just contain what it is. "This is a pistol with a silencer". This is not really an issue of the shr5rcp. Is this something we could add to the Chummer tasklist?

**Comment by UrsZeidler** [comment]
Yes of course, sounds reasonable.
