### ISSUE TITLE
Skill widget should not show not learned skills

### ISSUE THREAD

**Issue by NoxMortem** [UrsZeidler/shr5rcp#154]
Although the model possibly requires the informaiton it is very bad that the skill widgets shows all language skills, all knowledge skills although the character has not learned them.

Same problem for skills and skill groups.

**Comment by UrsZeidler** [comment]
You got the point.

When the character is committed theses pages should be replaced by a read only, more compact one.

**Comment by UrsZeidler** [comment]
added new persona page
