### ISSUE TITLE
It seems like damage can not be assigned

### ISSUE THREAD

**Issue by NoxMortem** [UrsZeidler/shr5rcp#157]

**Comment by UrsZeidler** [comment]
There is always the 'fallback' default form. 
But we could use the widget which displays the damage as input.

**Comment by NoxMortem** [comment]
I mean after requesting a damage resistance test no damage is assigned

Also there is no differentiation between physical and mental damage in the damage resistance test

**Comment by UrsZeidler** [comment]
You need to fill in the damage code , like 9P or 2M for mental.

**Comment by NoxMortem** [comment]
This still requires some sort of indicator. A GUI element which requires a specific formattor requires the use of a validation framework (there are several available for java) but this is expensive. Therefore I would recommend to split the damage Type into a combo box and the damage value into a value.

Or use greyed out default text which clears on the gainFocus event and fills in if it is empty on focusLost like "9P or 9M". The combobox option is less error prone and less to implement!

**Comment by UrsZeidler** [comment]
Normally the dialog get filled from the attack probe before, therefor the damage is also filled in, I want to add some validation to the command, the validation is free as it is part of the emf model framework we use. When we do some work on the dialogs we will add the validation.

Btw. there was also an error in the damage code parsing, mental damage was not recognized.
So good that you had it reopened.
