### ISSUE TITLE
Hide and remove eclipse views and perspective which are not relevant for the program

### ISSUE THREAD

**Issue by NoxMortem** [UrsZeidler/shr5rcp#158]
There is a ton of views and menu buttons which are part of the underlying engine but should be removed as they are not part of the shr5rcp!

Example:
The whole views in general
The model repository

I could be wrong but it looks like the just clutter the interface and make everything more complicated.

The ECP perspective looks like the basis for the Shadowrun Resources view

**Comment by UrsZeidler** [comment]
My understanding is, for this we need to move the 'application core' to e4 as this would give us complete control, by now we depend on these plugins and these are their contributions to the platform.
This is an issue of the old plugin structure of the eclipse 3.x core, which we use, sadly.
See #62
