### ISSUE TITLE
Script simulation

### ISSUE THREAD

**Issue by NoxMortem** [UrsZeidler/shr5rcp#159]
What is the purpose of this editor?

simulation not runable!!

Charakter Thugs & mouth breathers Right hand unset

Charakter Thugs & mouth breathers left hand unset

Charakter Thug lieutenant Right hand unset

Charakter Thug lieutenant left hand unset

Charakter Delvil Rat Right hand unset

Charakter Delvil Rat left hand unset

Charakter Ralf Right hand unset

Charakter Ralf left hand unset

Charakter Gangers & street scum Right hand unset

Charakter Gangers & street scum left hand unset

Charakter Gu Right hand unset

Charakter Gu left hand unset

Charakter Rob Right hand unset

Charakter Rob left hand unset

Charakter Kyra Right hand unset

Charakter Kyra left hand unset

Charakter Gu Right hand unset

Charakter Gu left hand unset

Charakter Rob Right hand unset

Charakter Rob left hand unset

Charakter Kyra Right hand unset

Charakter Kyra left hand unset

Charakter Ex-Firewatch Concept Right hand unset

Charakter Ex-Firewatch Concept left hand unset

Charakter Orc Sam 1 Right hand unset

Charakter Orc Sam 1 left hand unset

Charakter Tank Right hand unset

Charakter Tank left hand unset

Charakter Troll phsy adept Right hand unset

Charakter Troll phsy adept left hand unset

Charakter Decker Right hand unset

Charakter Decker left hand unset

**Comment by UrsZeidler** [comment]
Before a placement can be simulated, we check first for all constrains, so we check for both hands, and expect a weapon there, one is enough, then we check if the weapon has the usable skill set. This must be true for all characters.
In the simulation the characters alway fall back to melee, if for example running out of ammo.

There is no 'bare hands' option for now.
