### ISSUE TITLE
Script options widget

### ISSUE THREAD

**Issue by NoxMortem** [UrsZeidler/shr5rcp#160]
Each option can be added once but afterwards the options can be change to the same type. Also it seems like options have no impact on the script at the moment.

**Comment by UrsZeidler** [comment]
The only effect implemented by now is the 'homeground' feature which enables the 'manage inventory' in the webapp. But more will come. see closed  #113

I also will add a text in the default form, stating that this page is a debug page as it gets reflective  generated by the emf forms, and serves only the purpose to enable editing when the application does not. A kind of fallback. So this would be an emfforms issue. We cannot fix this here.
http://eclipse.org/ecp/emfforms/

**Comment by NoxMortem** [comment]
Couldn't we possibly hide all fallback forms and just show them in some sort of "Debug" view?

**Comment by UrsZeidler** [comment]
This we could do, I will add a preferences for it.
