### ISSUE TITLE
Context menu filtering and sorting

### ISSUE THREAD

**Issue by NoxMortem** [UrsZeidler/shr5rcp#164]
Beside that the context menu needs some more cleanup (right clicking on all is simply sick) it does require at least some alphabetical sorting (using the localized version)

This is a good system for 1-10 node types which are addable and also the add new model node at the shr5Resources node works great as the wizard guides the user through the process. This system does not work for the all or resourcen nodes.

**Comment by UrsZeidler** [comment]
This is also an issue for #112 as the model explorer is not in our hand.
