### ISSUE TITLE
Clean project from scratch and updates

### ISSUE THREAD

**Issue by NoxMortem** [UrsZeidler/shr5rcp#165]
See #110 regarding resource updates

To create a new project / campaign from scratch it is expected to keep the resources but to discard everything else.

We need a valid workflow for this. My current approach was:

1. Delete all nodes but all
2. Right click shr5Resources -> "Neues Modellelement" -> Player Management
3. Right click shr5Resources -> "Neues Modellelement" -> GM Management
4. Right click shr5Resources -> "Neues Modellelement" -> Scripts

Is this the correct way to do this?  If so, maybe it is possible to overload the "New Project" menu item and do exactly this. A "project" should be a one campaign, while a GM should be able to have a SET of campaigns he runs, to allow him to rereference nodes between campaigns. Each campaign therefore would contain those management nodes.

The Problem is this does not create any nodes in the tree! An editor opens but it is impossible to save the new object.

See https://github.com/UrsZeidler/shr5rcp/wiki/The-model for more information on the model.

We also need a workflow to export/import campaigns. I know it is possible to export/import child nodes but what would happen to all the references? (I will try this out but it might be a very good idea if you as the developer answer this as this is something REALLY important). If I am as a tester able to run my campaign without recreating it on every update I will test it much more efficiently.

**Comment by UrsZeidler** [comment]
To the important question, the references should be intact.

I would advice another approach,  as the management nodes are recursive, you could create a child for each campaign and name it properly.
![gamemastermanagement](https://cloud.githubusercontent.com/assets/6352038/5729961/c42847e2-9b76-11e4-9293-568f6f8404b1.png)


A script object is designed to be self contained, all resources, mostly npc's can be stored there, in the GamemasterManagement of the script.

![scripting class diagram](https://cloud.githubusercontent.com/assets/6352038/5729877/2bf4d0e4-9b76-11e4-8dcd-90afebcd16db.png)
