### ISSUE TITLE
Datei main menu needs a import root node menu item

### ISSUE THREAD

**Issue by NoxMortem** [UrsZeidler/shr5rcp#169]
There is no way to delete the whole tree and import some saved one. Without a root node the program becomes unuseable as it is impossible to add/create/import a root node

**Comment by UrsZeidler** [comment]
This is no usecase, for now you could switch the workspace by change the start parameter in the run_shr.ini file.

     -data
      shr_workspace/

You could also use an absolute path. May be we will add the workspace switcher from eclipse.
