### ISSUE TITLE
Shr5 System node and all subnodes require localization nodes

### ISSUE THREAD

**Issue by NoxMortem** [UrsZeidler/shr5rcp#174]
Currently it is not possible to add localization nodes

**Comment by UrsZeidler** [comment]
duplicate of #170

**Comment by UrsZeidler** [comment]
Looks a bit odd in the model explorer. So I made a task in #112 
![shr5 idetifiable](https://cloud.githubusercontent.com/assets/6352038/5925563/abb20088-a664-11e4-8a0f-c6a7925e7b6a.png)
