### ISSUE TITLE
Munition requires a range

### ISSUE THREAD

**Issue by NoxMortem** [UrsZeidler/shr5rcp#191]
I am not sure but this is not covered by the shadowrun base (at least i think it is that way)

**Comment by UrsZeidler** [comment]
The range is the closest discriminator as a kind of category, the ammunition can be exchange between model of the same category.

_or simplicity, each kind of gun can trade ammo with
another of its class: for example, all heavy pistols can
share ammo._

from core rules 433

**Comment by NoxMortem** [comment]
I do very much recommend to use a own weapon category instead of to misuse the ranges just because there is a 1:1 relation. In Shadowrun 5 it was defined very unclear but at least in old resources books I stumpled upon the very clear "munition for MP" texts. This does not necessarily require any change in the model but maybe we could update the View-Layer to give the user a better explanation. Like "Type" as a label instead of "Range".
