### ISSUE TITLE
Grouped skills bug : It is not possible to set a skill to a level different than the group

### ISSUE THREAD

**Issue by NoxMortem** [UrsZeidler/shr5rcp#196]
It is impossible to create a character with a skill inside of a skill group. The rule do permit this and also permit advancement with karma.

**Comment by UrsZeidler** [comment]
Yeah,
_In addition, skill groups cannot be
broken up in this step, so individual skill points cannot
raise the ratings of skills purchased as a group. (Note
that skill groups can be broken up in Step Seven: Spend
Your Left Over Karma (p. 98)._

From p. 88
