### ISSUE TITLE
The skill exotic weapon

### ISSUE THREAD

**Issue by NoxMortem** [UrsZeidler/shr5rcp#197]
The display of skills exotic weapon in the character generator does not make much sense as actually this skill has to be taken once for every specific exotic weapon -> which requires to add a new skill to the model

**Comment by UrsZeidler** [comment]
Do you have a list ?
We could add them to the xslt magic and add them.

**Comment by UrsZeidler** [comment]
I found a list: 
http://www.reddit.com/r/Shadowrun/comments/30sshs/exotic_weapons/

Exotic Melee

    AA Combat Chainsaw
    AA Monofilament Chainsaw
    Ballistic Shield
    All 4 battering rams
    Blast shield
    Bullwhip
    Garrote
    Mono. Chainsaw
    Mono. Whip
    Mono. Garotte
    Riot Shield

Exotic Ranged

    Screech Sonic Rifle
    Super Squirt
    Blowgun
    Bola
    Pain Inducer
    Gyrojet Pistol
    Grapple Gun
    Hold-fast Sprayer
    Gun Cane
    Knockoff gun cane
    Mono. Bola
    Parashield Dart Pistol
    Parashield Dart Rifle
    Reatrius Net Gun
    Retarius Net Gun XL
    Shooting Bracers
