### ISSUE TITLE
Character nodes can have different values

### ISSUE THREAD

**Issue by NoxMortem** [UrsZeidler/shr5rcp#200]
This is one of the biggest thing i think are really shitty at the current system because it is extremly confusing.

A character named Test generated with the Shr5 Generator will create a node SC Magier Test which a sub node Magier Test. Also we have the Generator node which again has multiple views which look redundant.

The node SC Magier Test can have different values than the Magier Test.

A new user can not really know how to use this part of the software.

Example: SC Magier Test has the value Acting 3 which creates a new node Gruppe Acting below the Magier Test node, but the Magier test node still has acting 0.

Deleting the Acting Group node will update the Magier Acting Group to 3 but now the model has no acting group node which seems not to be expected.

The value is only editable if the correct skill is selected first. Very confusing. The user sees a value of -1 and can not click it... but if he selects it first he can. This is only ok if all cells are greyed but the one row you selected.

Also it would be way better to ADD skills instead of setting the values as in the current system. This really needs a lot of rework.

**Comment by UrsZeidler** [comment]
As I sayed before the model explorer displays the whole structure of the objects, as it is a generic component I 'borrowed' from the ecp project.
And the inner structure of the manage character looks like this:
![managed character](https://cloud.githubusercontent.com/assets/6352038/5785114/45d59dae-9dd3-11e4-9676-b07a94f98026.png)
The managed character contains a persona which defines the type, in your example the node 'Magier Test' the Generator is stored in the character when the generation process in done, to keep all the information about the choises.

So this is solved with #112
