### ISSUE TITLE
Why are character groups mandatory...

### ISSUE THREAD

**Issue by NoxMortem** [UrsZeidler/shr5rcp#201]
... but can add multiple Spieler nodes recursively (which makes really zero sense)
... but can only add Team and Grunt group to a Script and not players?

**Comment by UrsZeidler** [comment]
1. A character group has only pc and npc as possible child's.
But a player group, same for the gamemaster , is like a directory where you can structure your data by separating it. It's simple and clean. I will remove the constrain for the character group.

2. In the Teams the different partys are organized and so manageable in the placements where there are referred. Grunts are a special case as they are a team.
The players are not part of a script, they will be inserted when you start a script, by selection of the game master, or via upload in the webapp.

**Comment by NoxMortem** [comment]
I will have to take a deeper look into this issue and give you a clear explanation. The problem is i did expect it to act as a folder as the folder/file metaphor is one of the most easy to understand and well known metaphors. Once I have seen the version without a constraint and got time for the next release you can expect some new issue on this type :)
