### ISSUE TITLE
Can't edit spellcaster/techno/adept rules

### ISSUE THREAD

**Issue by TaeoG** [UrsZeidler/shr5rcp#214]
when creating a custom generator system, trying to edit an adept priority rule for example, it throws a null pointer error instead of creating the form. metatype, skills, attributes, resources all work fine.

**Comment by UrsZeidler** [comment]
You could get the development stream from this update site: https://buildhive.cloudbees.com/job/UrsZeidler/job/shr5rcp/lastSuccessfulBuild/artifact/de.urszeidler.shr5.updatesite/target/repository/

**Comment by TaeoG** [comment]
excellenr
