### ISSUE TITLE
Generate a multi page pdf

### ISSUE THREAD

**Issue by UrsZeidler** [UrsZeidler/shr5rcp#41]
The svg->pdf export need an enhancement to produce one pdf with several pages.

**Comment by NoxMortem** [comment]
I have worked with pdfbox already and it does work fine for merging and creating .pdfs from scratch.

It has a lot of problems and bugs with Acro Forms and there is not really good solution available freely. I would suggest to avoid Adobe Forms for now as they introduce a lot of problems (I work on several little java pdf related tools and it is possible but a pain in the ass to generate high quality .pdf form features which behave as someone would expect it.)

**Comment by UrsZeidler** [comment]
Done in the last release.
